version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgres/data
networks:
  postgres-compose-network:
    driver: bridge